spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://localhost:5432/ifitness-user-db
    username: postgres
    password: cocoMELON1@

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

